import type { ConfigFormState } from './types'
import { collectConfig } from './collect'

const ENV_ORDER = [
  'HTTP_PORT', 'METRICS_PORT', 'MITM_ENABLED', 'SHUTDOWN_TIMEOUT_SECONDS', 'RUST_LOG',
  'CACHE_CAPACITY', 'CACHE_TTL_SECONDS', 'MAX_CACHE_BODY_SIZE', 'CACHE_SHARDS',
  'CACHE_HONOR_CACHE_CONTROL', 'NEGATIVE_CACHE_ENABLED', 'NEGATIVE_CACHE_TTL_SECONDS',
  'CACHE_SPILL_THRESHOLD_BYTES',
  'REDIS_L2_ENABLED', 'REDIS_URL', 'REDIS_KEY_PREFIX',
  'WORKER_COUNT', 'PERF_FAST_CACHE_HIT', 'STREAMING_MISS_ENABLED',
  'KAFKA_SAMPLE_RATE', 'METRICS_SAMPLE_RATE', 'KAFKA_QUEUE_CAPACITY',
  'KAFKA_BROKERS', 'KAFKA_TOPIC', 'KAFKA_ACKS',
  'AUTH_ENABLED', 'AUTH_BACKEND', 'AUTH_REALM', 'AUTH_CACHE_TTL',
  'LDAP_SERVERS', 'LDAP_BASE_DN', 'LDAP_BIND_DN', 'LDAP_BIND_PASSWORD',
  'LDAP_USER_FILTER', 'LDAP_USE_TLS',
  'NTLM_DOMAIN', 'NTLM_WORKSTATION',
  'ACL_ENABLED', 'ACL_DEFAULT_ACTION', 'ACL_RULES_PATH', 'ACL_AUTO_RELOAD',
  'ACL_RELOAD_INTERVAL', 'ACL_API_TOKEN',
  'CATEGORIZATION_ENABLED', 'CATEGORIZATION_CACHE_TTL',
  'UT1_ENABLED', 'UT1_PATH', 'URLHAUS_ENABLED', 'URLHAUS_API',
  'PHISHTANK_ENABLED', 'PHISHTANK_API', 'PHISHTANK_API_KEY', 'CUSTOM_DB_ENABLED', 'CUSTOM_DB_PATH',
] as const

export function formatEnv(form: ConfigFormState): string {
  const config = collectConfig(form)
  const lines = [
    '# Generated by BSDM Admin Console',
    '# See packaging/config/bsdm-proxy.env.example for full reference',
    '',
  ]
  const written = new Set<string>()

  for (const key of ENV_ORDER) {
    if (config[key] !== undefined && config[key] !== '') {
      lines.push(`${key}=${config[key]}`)
      written.add(key)
    }
  }
  for (const [key, value] of Object.entries(config)) {
    if (!written.has(key) && value !== '') {
      lines.push(`${key}=${value}`)
    }
  }

  return lines.join('\n') + '\n'
}

function proxyEnvBlock(config: ReturnType<typeof collectConfig>): string {
  const keys = [
    'HTTP_PORT', 'METRICS_PORT', 'RUST_LOG', 'MITM_ENABLED', 'SHUTDOWN_TIMEOUT_SECONDS',
    'CACHE_CAPACITY', 'CACHE_TTL_SECONDS', 'MAX_CACHE_BODY_SIZE', 'CACHE_SHARDS',
    'CACHE_HONOR_CACHE_CONTROL', 'NEGATIVE_CACHE_ENABLED', 'NEGATIVE_CACHE_TTL_SECONDS',
    'CACHE_SPILL_THRESHOLD_BYTES', 'REDIS_L2_ENABLED', 'REDIS_URL', 'REDIS_KEY_PREFIX',
    'WORKER_COUNT', 'PERF_FAST_CACHE_HIT', 'STREAMING_MISS_ENABLED',
    'KAFKA_SAMPLE_RATE', 'METRICS_SAMPLE_RATE', 'KAFKA_QUEUE_CAPACITY',
    'KAFKA_BROKERS', 'KAFKA_TOPIC', 'KAFKA_ACKS',
    'AUTH_ENABLED', 'AUTH_BACKEND', 'AUTH_REALM', 'AUTH_CACHE_TTL',
    'LDAP_SERVERS', 'LDAP_BASE_DN', 'LDAP_BIND_DN', 'LDAP_BIND_PASSWORD',
    'LDAP_USER_FILTER', 'LDAP_USE_TLS', 'NTLM_DOMAIN', 'NTLM_WORKSTATION',
    'ACL_ENABLED', 'ACL_DEFAULT_ACTION', 'ACL_RULES_PATH', 'ACL_AUTO_RELOAD',
    'ACL_RELOAD_INTERVAL', 'ACL_API_TOKEN',
    'CATEGORIZATION_ENABLED', 'CATEGORIZATION_CACHE_TTL', 'UT1_ENABLED', 'UT1_PATH',
    'URLHAUS_ENABLED', 'URLHAUS_API', 'PHISHTANK_ENABLED', 'PHISHTANK_API', 'PHISHTANK_API_KEY',
    'CUSTOM_DB_ENABLED', 'CUSTOM_DB_PATH',
  ]
  return keys
    .filter((k) => config[k] !== undefined && config[k] !== '')
    .map((k) => `      - ${k}=${config[k]}`)
    .join('\n')
}

export function generateDockerCompose(form: ConfigFormState): string {
  const config = collectConfig(form)
  const prom = config.PROMETHEUS_ENABLED === 'true'
  const graf = config.GRAFANA_ENABLED === 'true'

  return `services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.9.8
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks: [bsdm-net]
    restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka:7.9.8
    depends_on: [zookeeper]
    ports: ["9092:9092"]
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks: [bsdm-net]
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "kafka-broker-api-versions --bootstrap-server localhost:9092 >/dev/null 2>&1"]
      interval: 10s
      timeout: 10s
      retries: 12
      start_period: 30s

  clickhouse:
    image: clickhouse/clickhouse-server:24.12
    ports: ["8123:8123", "9000:9000"]
    environment:
      CLICKHOUSE_DB: ${config.CLICKHOUSE_DATABASE}
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - ./scripts/clickhouse/http_cache.sql:/docker-entrypoint-initdb.d/01-http_cache.sql:ro
    networks: [bsdm-net]
    restart: unless-stopped
${prom ? `
  prometheus:
    image: prom/prometheus:v2.55.1
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports: ["9091:9090"]
    networks: [bsdm-net]
    restart: unless-stopped
` : ''}${graf ? `
  grafana:
    image: grafana/grafana:11.4.0
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_AUTH_ANONYMOUS_ENABLED: "false"
    volumes:
      - ./grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml:ro
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
    ports: ["3000:3000"]
    depends_on: [prometheus]
    networks: [bsdm-net]
    restart: unless-stopped
` : ''}
  proxy:
    build:
      context: .
      dockerfile: Dockerfile
      target: proxy
    ports:
      - "${config.HTTP_PORT}:${config.HTTP_PORT}"
      - "${config.METRICS_PORT}:${config.METRICS_PORT}"
    environment:
${proxyEnvBlock(config)}
    volumes:
      - ./certs:/certs:ro
${config.ACL_ENABLED === 'true' ? `      - ./acl-rules.json:${config.ACL_RULES_PATH}:ro\n` : ''}${config.UT1_ENABLED === 'true' ? `      - ${config.UT1_PATH}:${config.UT1_PATH}:ro\n` : ''}${config.CUSTOM_DB_ENABLED === 'true' ? `      - ./custom-categories.json:${config.CUSTOM_DB_PATH}:ro\n` : ''}    depends_on:
      kafka:
        condition: service_healthy
    networks: [bsdm-net]
    restart: unless-stopped

  cache-indexer:
    build:
      context: .
      dockerfile: Dockerfile
      target: cache-indexer
    environment:
      - KAFKA_BROKERS=${config.KAFKA_BROKERS}
      - KAFKA_TOPIC=${config.KAFKA_TOPIC}
      - KAFKA_BATCH_SIZE=${config.KAFKA_BATCH_SIZE}
      - KAFKA_BATCH_TIMEOUT=${config.KAFKA_BATCH_TIMEOUT}
      - CLICKHOUSE_URL=${config.CLICKHOUSE_URL}
      - CLICKHOUSE_DATABASE=${config.CLICKHOUSE_DATABASE}
      - CLICKHOUSE_TABLE=${config.CLICKHOUSE_TABLE}
${config.SEARCH_API_TOKEN ? `      - SEARCH_API_TOKEN=${config.SEARCH_API_TOKEN}\n` : ''}    depends_on: [kafka, clickhouse]
    networks: [bsdm-net]
    restart: unless-stopped

volumes:
  clickhouse-data:

networks:
  bsdm-net:
    driver: bridge
`
}

export function generateAclRules(form: ConfigFormState): { default_action: string; rules: object[] } | null {
  if (!form.aclEnabled) return null

  const rules: object[] = []
  let priority = 100

  const addCategory = (id: string, name: string, category: string, enabled: boolean) => {
    if (!enabled) return
    rules.push({
      id,
      name,
      enabled: true,
      priority: priority++,
      action: 'deny',
      rule_type: { Category: category },
      redirect_url: null,
      comment: null,
    })
  }

  addCategory('block-malware', 'Block malware URLs', 'malware', form.aclBlockMalware)
  addCategory('block-phishing', 'Block phishing URLs', 'phishing', form.aclBlockPhishing)
  addCategory('block-adult', 'Block adult content', 'adult', form.aclBlockAdult)
  addCategory('block-gambling', 'Block gambling sites', 'gambling', form.aclBlockGambling)

  return { default_action: form.aclDefaultAction, rules }
}

export function downloadFile(filename: string, content: string): void {
  const blob = new Blob([content], { type: 'text/plain' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}
