export interface ProxyConfig {
  HTTP_PORT: string
  METRICS_PORT: string
  RUST_LOG: string
  SHUTDOWN_TIMEOUT_SECONDS: string
  MAX_CACHE_BODY_SIZE: string
  MITM_ENABLED: string
  CACHE_CAPACITY: string
  CACHE_TTL_SECONDS: string
  CACHE_SHARDS: string
  CACHE_HONOR_CACHE_CONTROL: string
  NEGATIVE_CACHE_ENABLED: string
  NEGATIVE_CACHE_TTL_SECONDS: string
  CACHE_SPILL_THRESHOLD_BYTES: string
  WORKER_COUNT: string
  PERF_FAST_CACHE_HIT: string
  STREAMING_MISS_ENABLED: string
  KAFKA_SAMPLE_RATE: string
  METRICS_SAMPLE_RATE: string
  KAFKA_QUEUE_CAPACITY: string
  KAFKA_BROKERS: string
  KAFKA_TOPIC: string
  KAFKA_ACKS: string
  KAFKA_BATCH_SIZE: string
  KAFKA_BATCH_TIMEOUT: string
  AUTH_ENABLED: string
  AUTH_BACKEND: string
  AUTH_REALM: string
  AUTH_CACHE_TTL: string
  ACL_ENABLED: string
  ACL_DEFAULT_ACTION: string
  ACL_RULES_PATH: string
  ACL_AUTO_RELOAD: string
  ACL_RELOAD_INTERVAL: string
  CATEGORIZATION_ENABLED: string
  CATEGORIZATION_CACHE_TTL: string
  UT1_ENABLED: string
  UT1_PATH: string
  URLHAUS_ENABLED: string
  URLHAUS_API: string
  PHISHTANK_ENABLED: string
  PHISHTANK_API: string
  PHISHTANK_API_KEY: string
  CUSTOM_DB_ENABLED: string
  CUSTOM_DB_PATH: string
  CLICKHOUSE_URL: string
  CLICKHOUSE_DATABASE: string
  CLICKHOUSE_TABLE: string
  PROMETHEUS_ENABLED: string
  GRAFANA_ENABLED: string
  ICAP_ENABLED: string
  ICAP_URL: string
  ICAP_FAIL_OPEN: string
  ICAP_REQMOD: string
  ICAP_RESPMOD: string
  ALERT_WORKER_ENABLED: string
  ALERT_WEBHOOK_URL: string
  AI_CACHE_ENABLED: string
  OLLAMA_URL: string
  QDRANT_URL: string
  RKN_SYNC_ENABLED: string
  RKN_SYNC_URL: string
  DOH_ENABLED: string
  DOH_BIND: string
  DOT_ENABLED: string
  DOT_BIND: string
  [key: string]: string
}

export interface ConfigFormState {
  httpPort: string
  metricsPort: string
  logLevel: string
  shutdownTimeout: string
  maxBodySizeMb: string
  mitmEnabled: boolean
  cacheCapacity: string
  cacheTtl: string
  cacheShards: string
  cacheHonorCacheControl: boolean
  negativeCacheEnabled: boolean
  negativeCacheTtl: string
  spillThresholdKb: string
  redisL2Enabled: boolean
  redisUrl: string
  redisKeyPrefix: string
  workerCount: string
  perfFastCacheHit: boolean
  streamingMissEnabled: boolean
  kafkaSampleRate: string
  metricsSampleRate: string
  kafkaQueueCapacity: string
  kafkaBrokers: string
  kafkaTopic: string
  kafkaAcks: string
  kafkaBatchSize: string
  kafkaBatchTimeout: string
  authEnabled: boolean
  authBackend: string
  authRealm: string
  authCacheTtl: string
  ldapServers: string
  ldapBaseDn: string
  ldapBindDn: string
  ldapBindPassword: string
  ldapUserFilter: string
  ldapUseTls: boolean
  ntlmDomain: string
  ntlmWorkstation: string
  aclEnabled: boolean
  aclDefaultAction: string
  aclRulesPath: string
  aclAutoReload: boolean
  aclReloadInterval: string
  aclApiToken: string
  aclBlockAdult: boolean
  aclBlockGambling: boolean
  aclBlockMalware: boolean
  aclBlockPhishing: boolean
  aclBlockRkn: boolean
  categorizationEnabled: boolean
  categorizationCacheTtl: string
  ut1Enabled: boolean
  ut1Path: string
  urlhausEnabled: boolean
  urlhausApi: string
  phishtankEnabled: boolean
  phishtankApi: string
  phishtankApiKey: string
  customDbEnabled: boolean
  customDbPath: string
  clickhouseUrl: string
  clickhouseDatabase: string
  clickhouseTable: string
  searchApiToken: string
  prometheusEnabled: boolean
  grafanaEnabled: boolean
  // Upstream TLS / HTTP
  upstreamCaCert: string
  upstreamHttp2Enabled: boolean
  preserveHeaderCase: boolean
  // Threat score enforcement (ml-worker write-back)
  threatScoreEnabled: boolean
  threatScorePollUrl: string
  threatScorePollInterval: string
  threatScoreBlockThreshold: string
  threatScoreWarnThreshold: string
  // Cache hierarchy (ICP/HTCP)
  hierarchyPeersPath: string
  icpServerEnabled: boolean
  icpBind: string
  htcpServerEnabled: boolean
  htcpBind: string
  peerDiscoveryEnabled: boolean
  peerDiscoveryMulticast: string
  // Rate limiting
  rateLimitEnabled: boolean
  rateLimitMaxKeys: string
  // eBPF / XDP
  ebpfXdpEnabled: boolean
  ebpfXdpIface: string
  ebpfXdpMode: string
  // Wasm request hooks
  wasmEnabled: boolean
  wasmModulePath: string
  wasmFailOpen: boolean
  wasmFuel: string
  // gRPC control plane
  controlGrpcEnabled: boolean
  controlGrpcBind: string
  controlApiToken: string
  // ICAP Inspection
  icapEnabled: boolean
  icapUrl: string
  icapFailOpen: boolean
  icapReqmod: boolean
  icapRespmod: boolean
  // Alert Worker
  alertWorkerEnabled: boolean
  alertWebhookUrl: string
  // AI Cache
  aiCacheEnabled: boolean
  ollamaUrl: string
  qdrantUrl: string
  // RKN Sync
  rknSyncEnabled: boolean
  rknSyncUrl: string
  // DNS Sinkhole (Encrypted)
  dohEnabled: boolean
  dohBind: string
  dotEnabled: boolean
  dotBind: string
}

export const defaultFormState: ConfigFormState = {
  httpPort: '1488',
  metricsPort: '9090',
  logLevel: 'info,bsdm_proxy=info',
  shutdownTimeout: '30',
  maxBodySizeMb: '10',
  mitmEnabled: true,
  cacheCapacity: '10000',
  cacheTtl: '3600',
  cacheShards: '16',
  cacheHonorCacheControl: true,
  negativeCacheEnabled: true,
  negativeCacheTtl: '120',
  spillThresholdKb: '256',
  redisL2Enabled: false,
  redisUrl: 'redis://redis:6379',
  redisKeyPrefix: 'bsdm:http:',
  workerCount: '1',
  perfFastCacheHit: false,
  streamingMissEnabled: true,
  kafkaSampleRate: '0',
  metricsSampleRate: '0',
  kafkaQueueCapacity: '8192',
  kafkaBrokers: 'kafka:9092',
  kafkaTopic: 'cache-events',
  kafkaAcks: '1',
  kafkaBatchSize: '100',
  kafkaBatchTimeout: '5000',
  authEnabled: false,
  authBackend: 'basic',
  authRealm: 'BSDM-Proxy',
  authCacheTtl: '300',
  ldapServers: 'ldaps://dc.corp.local:636',
  ldapBaseDn: 'dc=corp,dc=local',
  ldapBindDn: 'cn=proxy,ou=services,dc=corp,dc=local',
  ldapBindPassword: '',
  ldapUserFilter: '(sAMAccountName={username})',
  ldapUseTls: true,
  ntlmDomain: 'WORKGROUP',
  ntlmWorkstation: 'PROXY01',
  aclEnabled: false,
  aclDefaultAction: 'allow',
  aclRulesPath: '/etc/bsdm-proxy/acl-rules.json',
  aclAutoReload: false,
  aclReloadInterval: '60',
  aclApiToken: '',
  aclBlockAdult: false,
  aclBlockGambling: false,
  aclBlockMalware: true,
  aclBlockPhishing: true,
  aclBlockRkn: false,
  categorizationEnabled: false,
  categorizationCacheTtl: '3600',
  ut1Enabled: true,
  ut1Path: '/var/lib/ut1-blacklists',
  urlhausEnabled: false,
  urlhausApi: 'https://urlhaus-api.abuse.ch/v1/url/',
  phishtankEnabled: false,
  phishtankApi: 'https://checkurl.phishtank.com/checkurl/',
  phishtankApiKey: '',
  customDbEnabled: false,
  customDbPath: '/etc/bsdm-proxy/custom-categories.json',
  clickhouseUrl: 'http://clickhouse:8123',
  clickhouseDatabase: 'bsdm',
  clickhouseTable: 'http_cache',
  searchApiToken: '',
  prometheusEnabled: true,
  grafanaEnabled: true,
  upstreamCaCert: '',
  upstreamHttp2Enabled: false,
  preserveHeaderCase: false,
  threatScoreEnabled: false,
  threatScorePollUrl: 'http://127.0.0.1:8091/api/threat-scores',
  threatScorePollInterval: '30',
  threatScoreBlockThreshold: '0.9',
  threatScoreWarnThreshold: '0.7',
  hierarchyPeersPath: '',
  icpServerEnabled: false,
  icpBind: '0.0.0.0:3130',
  htcpServerEnabled: false,
  htcpBind: '0.0.0.0:4827',
  peerDiscoveryEnabled: false,
  peerDiscoveryMulticast: '239.255.77.77:3132',
  rateLimitEnabled: false,
  rateLimitMaxKeys: '100000',
  ebpfXdpEnabled: false,
  ebpfXdpIface: 'eth0',
  ebpfXdpMode: 'driver',
  wasmEnabled: false,
  wasmModulePath: '/etc/bsdm-proxy/hooks.wasm',
  wasmFailOpen: true,
  wasmFuel: '1000000',
  controlGrpcEnabled: false,
  controlGrpcBind: '127.0.0.1:50051',
  controlApiToken: '',
  icapEnabled: false,
  icapUrl: 'icap://127.0.0.1:1344/echo',
  icapFailOpen: true,
  icapReqmod: true,
  icapRespmod: true,
  alertWorkerEnabled: false,
  alertWebhookUrl: '',
  aiCacheEnabled: false,
  ollamaUrl: 'http://127.0.0.1:11434',
  qdrantUrl: 'http://127.0.0.1:6333',
  rknSyncEnabled: false,
  rknSyncUrl: 'https://raw.githubusercontent.com/zapret-info/z-i/master/dump.csv',
  dohEnabled: false,
  dohBind: '0.0.0.0:8443',
  dotEnabled: false,
  dotBind: '0.0.0.0:853',
}
