-- M4 threat / SOC example queries for bsdm.http_cache
-- Run ad-hoc or wire into Grafana alerts / materialized views later.

-- Top blocked categories (7d)
-- SELECT arrayJoin(categories) AS category, count() AS events
-- FROM bsdm.http_cache
-- WHERE ts >= now() - INTERVAL 7 DAY
--   AND acl_action IN ('deny', 'redirect')
-- GROUP BY category
-- ORDER BY events DESC
-- LIMIT 20;

-- Burst domains: same domain > N requests / 5 minutes from one client
-- SELECT
--   client_ip,
--   domain,
--   count() AS requests,
--   min(ts) AS first_ts,
--   max(ts) AS last_ts
-- FROM bsdm.http_cache
-- WHERE ts >= now() - INTERVAL 1 HOUR
-- GROUP BY client_ip, domain
-- HAVING requests >= 50
-- ORDER BY requests DESC
-- LIMIT 100;

-- Off-hours traffic (UTC): 22:00–06:00 with threat sources
-- SELECT ts, username, client_ip, domain, url, threat_sources, categories
-- FROM bsdm.http_cache
-- WHERE ts >= now() - INTERVAL 7 DAY
--   AND (toHour(ts) >= 22 OR toHour(ts) < 6)
--   AND length(threat_sources) > 0
-- ORDER BY ts DESC
-- LIMIT 200;

-- High-entropy domains:
-- 1) SQL prefilter: length(domain) >= 16 (or ALERT_HIGH_ENTROPY_MIN_DOMAIN_LEN)
-- 2) alert-worker post-filter: Shannon entropy on leftmost label (ALERT_SHANNON_MIN_BITS)
--    and/or legacy digit-run heuristic (ALERT_HIGH_ENTROPY_MODE=shannon|legacy|either)
-- SELECT domain, count() AS requests, uniqExact(client_ip) AS clients
-- FROM bsdm.http_cache
-- WHERE ts >= now() - INTERVAL 1 DAY
--   AND length(domain) >= 16
-- GROUP BY domain
-- HAVING requests >= 5
-- ORDER BY requests DESC
-- LIMIT 50;

-- Wired into alert-worker rules (blocked_burst, domain_burst, off_hours_threat,
-- high_entropy_domain, beacon_periodic). See docs/alerting.md.

-- Periodic C&C beacon candidates (client→domain regular gaps)
-- WITH ordered AS (
--   SELECT
--     toString(client_ip) AS client_ip,
--     domain,
--     ts,
--     dateDiff(
--       'second',
--       lagInFrame(ts) OVER (PARTITION BY client_ip, domain ORDER BY ts),
--       ts
--     ) AS gap_sec
--   FROM bsdm.http_cache
--   WHERE ts >= now() - INTERVAL 1 HOUR
--     AND domain != ''
-- )
-- SELECT
--   client_ip,
--   domain,
--   count() AS gaps,
--   avg(gap_sec) AS avg_gap,
--   if(avg(gap_sec) = 0, 1, stddevPop(gap_sec) / avg(gap_sec)) AS gap_cv
-- FROM ordered
-- WHERE gap_sec IS NOT NULL
--   AND gap_sec BETWEEN 45 AND 900
-- GROUP BY client_ip, domain
-- HAVING gaps >= 5 AND gap_cv <= 0.25
-- ORDER BY gaps DESC
-- LIMIT 100;
