{{- if and .Values.mlWorker .Values.mlWorker.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bsdm.fullname" . }}-ml-worker
  labels:
    {{- include "bsdm.labels" . | nindent 4 }}
    app.kubernetes.io/component: ml-worker
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.mlWorker.service.port }}
      targetPort: admin
      protocol: TCP
      name: admin
  selector:
    {{- include "bsdm.mlWorkerSelectorLabels" . | nindent 4 }}
{{- end }}
