{{- if and (gt (int .Values.replicaCount) 0) .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "bsdm.fullname" . }}
  labels:
    {{- include "bsdm.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "bsdm.selectorLabels" . | nindent 6 }}
{{- end }}
