apiVersion: v1
kind: Service
metadata:
  name: {{ include "bsdm.fullname" . }}
  labels:
    {{- include "bsdm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  ports:
    - name: proxy
      port: {{ .Values.service.proxyPort }}
      targetPort: proxy
      protocol: TCP
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "bsdm.selectorLabels" . | nindent 4 }}
