apiVersion: v2
name: bsdm
description: BSDM-Proxy forward proxy with optional Redis L2
type: application
version: 0.1.2
appVersion: "0.5.0"
keywords:
  - proxy
  - cache
  - swg
maintainers:
  - name: onixus
    url: https://github.com/onixus/bsdm-proxy
